### ISSUE TITLE
Review Me

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvistaqt#1]
@pyvista/developers, I'd like you to please take a look at this repo as it's the execution of the other half of https://github.com/pyvista/pyvista/pull/719

**Comment by GuillaumeFavelier** [comment]
I'm on it

**Comment by akaszynski** [comment]
Going to need `pyvista==0.25.0` for automated testing to work, but tests pass locally.  Some work on the docs would be nice, but it's already a little better than before.
