### ISSUE TITLE
Release 0.5?

### ISSUE THREAD

**Issue by larsoner** [pyvista/pyvistaqt#117]
@pyvista/collaborators okay to release 0.5.0 now that pyvista 0.31 is out? Repos I work on are getting DeprecationWarnings due to the rcParams that were fixed a few weeks ago.

**Comment by GuillaumeFavelier** [comment]
I'm +1 for this @larsoner, `pyvistaqt 0.4` just followed `pyvista 0.30` so I think this is a good idea to follow along the changes (especially if some adjustments were necessary in `pyvistaqt`).

**Comment by larsoner** [comment]
@akaszynski I tagged 0.5.0 but do not have PyPi permissions, can you add me as an admin for pyvistaqt (Eric89GXL)?

**Comment by akaszynski** [comment]
Added you as an owner, @larsoner.

**Comment by larsoner** [comment]
Forgot it's done automagically by Azure

https://github.com/pyvista/pyvistaqt/blob/master/.ci/azure-pipelines.yml#L94

But probably good to have me as a backup in any case! :)

**Comment by akaszynski** [comment]
> But probably good to have me as a backup in any case! :)

Absolutely.  Bane and I did the same thing for pyvista.
