### ISSUE TITLE
Cannot see vtkCameraOrientationWidget when using QtInteractor

### ISSUE THREAD

**Issue by ventorvar** [pyvista/pyvistaqt#132]
Initially, I thought this was a `pyvista` issue overall however after getting some [feedback](https://github.com/pyvista/pyvista/discussions/1892) it looks like the `vtkCameraOrientationWidget` works just fine with base `pyvista`.  Using the following minimal example, I get an expected Qt window with the plot inside, but the camera orientation widget is not displayed.

```python
import sys
from qtpy import QtWidgets

import pyvista
import pyvistaqt
from vtkmodules.vtkInteractionWidgets import vtkCameraOrientationWidget


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        plotter = pyvistaqt.QtInteractor()
        plotter.add_mesh(pyvista.Cube())
        cam_orient_widget = vtkCameraOrientationWidget()
        cam_orient_widget.SetParentRenderer(plotter.renderer)
        cam_orient_widget.On()

        widget = QtWidgets.QWidget(self)
        vlayout = QtWidgets.QVBoxLayout()
        vlayout.addWidget(plotter)
        widget.setLayout(vlayout)
        self.setCentralWidget(widget)


if __name__ == '__main__':
    app = QtWidgets.QApplication()
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
```

![image](https://user-images.githubusercontent.com/44443959/143977650-e1fcb540-404c-445a-b1e3-add38e8194f3.png)

### Expected (non-pyvistaqt) result
![image](https://user-images.githubusercontent.com/44443959/143977610-e70c4388-ae63-415b-8cc8-d0b1174b8635.png)

**Comment by akaszynski** [comment]
BTW, this feature will be added in https://github.com/pyvista/pyvista/pull/1899 and will work natively in a `pyvistaqt.BackgroundPlotter`.
