### ISSUE TITLE
Q: Release

### ISSUE THREAD

**Issue by larsoner** [pyvista/pyvistaqt#134]
Any objection to making a release so that we can get one out that includes https://github.com/pyvista/pyvistaqt/pull/127 ?

**Comment by akaszynski** [comment]
No issues. @GuillaumeFavelier do you want me to take care of that?

**Comment by GuillaumeFavelier** [comment]
> Any objection to making a release 

I have no objection either.

> do you want me to take care of that?

You can go ahead @akaszynski :+1:

**Comment by banesullivan** [comment]
Do we not have automated deployments for this?

**Comment by banesullivan** [comment]
Circle CI should handle it: https://github.com/pyvista/pyvistaqt/blob/3ab85370a67d0613b9488272f935442b6e29ef61/.ci/azure-pipelines.yml#L94

Just bump the version and push a tag and all should be handled

**Comment by GuillaumeFavelier** [comment]
If you do not mind to wait a bit longer, I would like to spend a bit more time on https://github.com/pyvista/pyvistaqt/pull/136 before the release. It's all about having more reliable CIs so I think it benefits the projects :pray:

**Comment by GuillaumeFavelier** [comment]
I had to push a last minute hotfix for Azure because of `vs2017-win2016` (terrible timing).

I updated `pyvistaqt/_version.py` and pushed the tag `0.6.0` on `main`, tt should be getting deployed right now! :+1:
