### ISSUE TITLE
Inaccurate docstring for the 'auto_update' argument of QtInteractor, BackgroundPlotter, and MultiPlotter

### ISSUE THREAD

**Issue by p-j-smith** [pyvista/pyvistaqt#141]
The docstrings for these classes states:

```
    auto_update :
        Automatic update rate in seconds.  Useful for automatically
        updating the render window when actors are change without
        being automatically ``Modified``.
```

However, in [the implementation of `auto_update`](https://github.com/pyvista/pyvistaqt/blob/main/pyvistaqt/plotting.py#L272-L282), the value of `auto_update` is raised to the power of `-1`:
```py
twait = int((auto_update ** -1) * 1000.0)
```
meaning that `auto_update` actually specifies the number of updates per second (larger values = more updates), rather than the update rate in seconds (larger values = fewer updates).

I'm not sure if this is an issue with the docs or with the implementation?

**Comment by GuillaumeFavelier** [comment]
I agree with you @p-j-smith, it can be misleading. I think the documentation can be updated to clarify this.

cc @hoechenberger

**Comment by hoechenberger** [comment]
+1 this is confusing; in fact, @GuillaumeFavelier and I were tripped by this just a few days ago!
