### ISSUE TITLE
Change name of the polydata in the BackgroundPlotter editor

### ISSUE THREAD

**Issue by Vysakh5391** [pyvista/pyvistaqt#148]
Is there a way to change the name of the `polydata `in the `backgroundplotter `editor?
![image](https://user-images.githubusercontent.com/47824150/156203378-1c2b40ed-8f78-4535-b370-90f5149efed6.png)
Any help would be appreciated!
Thanks!

**Comment by GuillaumeFavelier** [comment]
@Vysakh5391 you probably found the solution yourself but for future reference, I will still explain it.

It is possible to use the `name` parameter of the `add_mesh()` function to set the name of a dataset:

```py
import pyvista as pv
from pyvistaqt import BackgroundPlotter

plotter = BackgroundPlotter()
plotter.add_mesh(pv.Box(), name='myBox')  # <-- name here
```

![image](https://user-images.githubusercontent.com/18143289/161775188-bf6e2a55-d78b-488c-8a21-6a011b26b674.png)
