### ISSUE TITLE
BackgroundPlotter not workin on Mac with vtk9

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvistaqt#15]
I *still* cannot get the `BackgrounPlotter` to work with VTK9.0 on Mac. See https://github.com/pyvista/pyvista/issues/562#issuecomment-619428242

cc @Leguark, since you all are using the `BackgroundPlotter` in GemPy, you may want to limit `vtk` in your setup.py until we get this fixed: `vtk<9.0.0`

cc @GuillaumeFavelier, are you all seeing this with MNE-Python?

**Comment by GuillaumeFavelier** [comment]
I know that we have a job on Travis configured with `vtk 9.0.0` for `MacOS` but I'm not 100% sure it runs all the tests, it might skip a lot. We still have to get reports from users on `MacOS` that did the upgrade to `vtk 9.0.0`

**Comment by GuillaumeFavelier** [comment]
To move forward with this one, @banesullivan could you maybe try a very simple example like the default [QVTKRenderWidgetConeExample](https://gitlab.kitware.com/vtk/vtk/-/blob/master/Wrapping/Python/vtkmodules/qt/QVTKRenderWindowInteractor.py#L546-582) and confirm that everything works fine for you?

I think the priority here is to understand *where* is the issue.

**Comment by larsoner** [comment]
Possibly related to initialize/start/show ordering?

https://discourse.vtk.org/t/vtk-9-pyqt-macos-no-rendering/3358/22

**Comment by larsoner** [comment]
(This thread also explains why macOS rendering worked for me at one point when building the wheels myself, but stopped working once I switched to using the official VTK wheels)

**Comment by cbrnr** [comment]
FWIW, toggling the "Eye Dome Lighting" setting made a figure change from completely black to actually show the figure correctly.

**Comment by banesullivan** [comment]
Thanks for the tip, @cbrnr - I will have to look into why that is...

-----

FYI: VTK 9.0.1 fixed this issue for me (see https://github.com/pyvista/pyvistaqt/pull/16#issuecomment-651149656) but @larsoner is still having trouble?

**Comment by larsoner** [comment]
I'm still having trouble with MNE examples, but it might be something we're doing at our end

**Comment by larsoner** [comment]
Okay I figured out the problem, `enable_anti_aliasing` gives be a black canvas:
```
import pyvista as pv
from pyvistaqt import BackgroundPlotter

p = BackgroundPlotter()
p.enable_anti_aliasing()
p.add_mesh(pv.Cone())
```

**Comment by larsoner** [comment]
... and also the VTK widget controls we have are only controllable by mouse clicks at 1/2 the correct location, meaning the VTK has some HiDPI problem with its widget controls and clicks...

**Comment by cbrnr** [comment]
And if you then toggle eyedome lighting, it works!

**Comment by larsoner** [comment]
The widgets work? Or antialiasing works? Or you need AA off / commented out plus eyedome toggle to see the simple example above?

**Comment by cbrnr** [comment]
[Your example](https://github.com/pyvista/pyvistaqt/issues/15#issuecomment-651227725) initially looks like this:

<img width="1136" alt="Screen Shot 2020-06-29 at 20 59 44" src="https://user-images.githubusercontent.com/4377312/86045182-8121a200-ba4b-11ea-9be0-7be158ffacc0.png">

After clicking on View - Toggle Eye Dome Lighting, it looks like this:

<img width="1136" alt="Screen Shot 2020-06-29 at 20 59 55" src="https://user-images.githubusercontent.com/4377312/86045220-90085480-ba4b-11ea-98d6-c3547a71de0f.png">

**Comment by larsoner** [comment]
I think this was fixed by VTK in https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7420 / 9.1, so we might as well close I think
