### ISSUE TITLE
disable / pause rendendring 

### ISSUE THREAD

**Issue by MarkusZimmerDLR** [pyvista/pyvistaqt#192]
Dear pyvistaqt team,

I set up an interactive application using your pyvistaqt library.

```python
from qtpy import QtWidgets, QtGui

from pyvistaqt import QtInteractor, MainWindow

class Tool(MainWindow):
    def create_frame(self):
        self.frame = QtWidgets.QFrame()
        topHlayout = QtWidgets.QHBoxLayout()

        # add the pyvista interactor object
        self.plotter = QtInteractor(self.frame, shape=(1, self.n_major_wing_comp), border=True, border_color='k')
        self.plotter.enable_mesh_picking(callback=self.pick_callback, left_clicking=True, color='white')
        self.plotter.enable_parallel_projection()
        self.signal_close.connect(self.plotter.close)
        ...
```

Now, for an update of the whole scene, I need to clear and readd all meshes (~200) individually (iteratively).
However, as `plotter.show()` has already been called, each `plotter.add_mesh(egg)` call triggers the upstream update and the whole scene is being rendered. Thus, the whole scene is rendered ~200 times, slowing down the whole process.

I would like to call a method which pauses the rendering / upstream update until the adding of the meshes is complete - then update the entire scene at once.
I have been searching for a method, yet cannot find a pyvista method which wraps the equivalent vtk functionality.
Maybe you can point me in the right direction.

Cheers,
Markus

**Comment by larsoner** [comment]
Have you tried passing `render=False` to `add_mesh` and `remove_actor` (if you also do a remove)?

https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.add_mesh.html
https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.remove_actor.html

**Comment by MarkusZimmerDLR** [comment]
Awesome! This did the trick. Afterwards, one simply calls  `plotter.render()` and the scene is updated. 
So easy and right in front of my eyes...

Thanks for the lighting fast response!
