### ISSUE TITLE
Issues about BackgroundPlotter in pyvista

### ISSUE THREAD

**Issue by GuillaumeFavelier** [pyvista/pyvistaqt#2]
I think it would probably help the transition from [pyvista](https://github.com/pyvista/pyvista) if the issues about `BackgroundPlotter` were moved in here at some point in time?

What do you think @pyvista/developers ?

**Comment by akaszynski** [comment]
Agreed.

**Comment by banesullivan** [comment]
Agreed. I can take on this task

**Comment by akaszynski** [comment]
@banesullivan, we're ready to move the issues over.

**Comment by banesullivan** [comment]
I'll get on this tonight

**Comment by banesullivan** [comment]
We're only transferring open issues, correct?

**Comment by akaszynski** [comment]
> We're only transferring open issues, correct?

I think that sounds reasonable.
