### ISSUE TITLE
BUG: BackgroundPlotter does not handle HiDPI properly

### ISSUE THREAD

**Issue by larsoner** [pyvista/pyvistaqt#20]
This code:
```
import pyvista as pv
from pyvista import Plotter
# from pyvistaqt import BackgroundPlotter as Plotter

def callback(*args, **kwargs):
    print(args, kwargs)


p = Plotter()
p.add_box_widget(callback)
p.add_mesh(pv.Cone())
p.show()
```
Works just fine for picking and looks like:

<img width="624" alt="Screen Shot 2020-06-29 at 2 41 56 PM" src="https://user-images.githubusercontent.com/2365790/86043503-d5f6f580-ba16-11ea-9972-89022ba7408c.png">

Changing it to use BackgroundPlotter, the window is twice as big (fine), the same number of rendered pixels (I think? if so, bad), and click interactions are off by a factor of 2 (you have to click 50% of the width and 50% of the height to get the right part of the interactor):

![Jun-29-2020 14-54-37](https://user-images.githubusercontent.com/2365790/86044765-9204f000-ba18-11ea-94bd-25a2b4efa5b8.gif)

There is a lot of code in Mayavi designed to handle this based around `_pixel_ratio`:

https://github.com/enthought/mayavi/blob/master/tvtk/pyface/ui/qt4/QVTKRenderWindowInteractor.py#L250-L253

Presumably some or all of this needs to be adapted to get HiDPI support working. Does this seem like the best way to go?

**Comment by larsoner** [comment]
Actually it looks like a lot of this should be handled by VTK already:

https://gitlab.kitware.com/vtk/vtk/-/merge_requests/4201/diffs

So I'm confused why it's not for BackgroundPlotter, but is for Plotter. Maybe we need to see if #25 helps by being explicit about parenting or something

**Comment by larsoner** [comment]
... #25 does not help, but I still think it's useful for cleaning up inheritance

**Comment by larsoner** [comment]
Actually I suspect the problem might be that BasePlotter and vtkRenderWindowInteractor will both create a RenderWindow (!). I think the solution might be to init BasePlotter first, then pass the self.ren_win it creates to vtkRenderWindowInteractor...

**Comment by larsoner** [comment]
Okay that's not the problem :(

**Comment by larsoner** [comment]
Okay I think this might actually be a VTK problem, since the [EmbedPyQt example](https://vtk.org/Wiki/VTK/Examples/Python/Widgets/EmbedPyQt) also has this problem:

<details>

```

import sys
import vtk
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QMainWindow, QFrame, QVBoxLayout
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

class MainWindow(QMainWindow):

    def __init__(self, parent=None):
        super().__init__(parent)

        self.frame = QFrame(self)
        self.vl = QVBoxLayout()
        self.frame.setLayout(self.vl)
        self.vtkWidget = QVTKRenderWindowInteractor(self.frame)
        self.vl.addWidget(self.vtkWidget)

        self.ren = vtk.vtkRenderer()
        self.vtkWidget.GetRenderWindow().AddRenderer(self.ren)
        self.iren = self.vtkWidget.GetRenderWindow().GetInteractor()

        # Create source
        source = vtk.vtkSphereSource()
        source.SetCenter(0, 0, 0)
        source.SetRadius(5.0)

        # Create a mapper
        mapper = vtk.vtkPolyDataMapper()
        mapper.SetInputConnection(source.GetOutputPort())

        # Create an actor
        actor = vtk.vtkActor()
        actor.SetMapper(mapper)

        self.ren.AddActor(actor)

        self.ren.ResetCamera()

        self.frame.setLayout(self.vl)
        self.setCentralWidget(self.frame)

        self.show()
        self.iren.Initialize()

    def resizeEvent(self, event):
        super().resizeEvent(event)
        print(event.size().width(), event.size().height())
        ren_win = self.vtkWidget.GetRenderWindow()
        print(ren_win.GetSize())
        print(self.ren.GetSize())


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    sys.exit(app.exec_())
```

</details>

The interaction coordinates are wrong, and the rendering is not full-res. I wonder if we should make our own interactor class like Mayavi does...?

Also maybe I should check that embedding a Mayavi scene also works.

**Comment by larsoner** [comment]
Okay filed an upstream bug:

https://gitlab.kitware.com/vtk/vtk/-/issues/17953

@banesullivan if you can try the two code snippets there on a HiDPI machine and comment over there that it's also a problem for you it might help.

**Comment by larsoner** [comment]
(mayavi has the same problem, hence why I think it's essentially VTK's problem...)

**Comment by larsoner** [comment]
Indeed it appears to be a VTK adapter problem, the workaround for now at my end is to use PyQt5 < 5.14

**Comment by banesullivan** [comment]
Just now looking at this. I can at least reproduce the issue on my laptop

**Comment by larsoner** [comment]
Just a cross-ref here that we should check if having our own RWI in #149 or moving to PySide6 (or PyQt6 eventually?) magically takes care of this issue.

**Comment by GuillaumeFavelier** [comment]
Well this is encouraging:

> Qt 6 supports high-DPI displays on all platforms, and will automatically account for the display resolution when using higher level APIs such as Qt Widgets or Qt Quick. Applications only need to provide high-resolution assets, such as images and icons. The feature is always enabled.

https://doc.qt.io/qt-6/portingguide.html#high-dpi

**Comment by larsoner** [comment]
... and FYI the upstream issue is https://gitlab.kitware.com/vtk/vtk/-/issues/17953. If we do manage to fix this by messing with `rwi.py`, we should port the changes upstream to Kitware.

**Comment by larsoner** [comment]
This seems to work fine on PySide6 at least, but still not PyQt5. Maybe we can just hope to move to full support for PySide6 (and PyQt6) and just not worry about this at some point...

**Comment by larsoner** [comment]
... since it works on Qt6, I'll close this as wontfix, same as in the upstream https://gitlab.kitware.com/vtk/vtk/-/issues/17953
