### ISSUE TITLE
Please publish sdist on PyPI

### ISSUE THREAD

**Issue by hoechenberger** [pyvista/pyvistaqt#22]
Currently, only binary wheels are published on PyPI. Could you please also publish the source distribution? This is relevant for users trying to build `pyvistaqt` themselves, or for creating `conda-forge` packages.

Thank you!

**Comment by banesullivan** [comment]
Sorry about that. We made the switch to building wheels across PyVista projects, realized that problem and forgot to re-enable this for pyvistaqt

Relevant to #14
