### ISSUE TITLE
Online documentation not up to date

### ISSUE THREAD

**Issue by ixjlyons** [pyvista/pyvistaqt#243]
https://qtdocs.pyvista.org/ shows version 0.6.0dev, whereas the package is currently at 0.9.0. It appears to be automated through Azure Pipelines to push built docs to https://github.com/pyvista/pyvistaqt-docs, but it looks like that hasn't been done in a while.

**Comment by akaszynski** [comment]
Good point. Also, the docs theme really should be updated to the `pydata-sphinx-theme` used by the PyVista docs.

**Comment by ixjlyons** [comment]
Looks like this was fixed by #399
