### ISSUE TITLE
Coverage?

### ISSUE THREAD

**Issue by GuillaumeFavelier** [pyvista/pyvistaqt#29]
I think it would be nice to have visibility on the project coverage with a badge.

Also it seems that coverage is uploaded to codecov but what about codecov integration with the PRs?

**Comment by GuillaumeFavelier** [comment]
Locally, I ran:

```
pytest -v --cov pyvistaqt --cov-report html
```

And I notice `90%` ! 

![image](https://user-images.githubusercontent.com/18143289/86466516-0cdd4c00-bd34-11ea-97c3-d050d8647acf.png)

**Comment by akaszynski** [comment]
I can add this.

**Comment by GuillaumeFavelier** [comment]
Has the coverage been uploaded correctly? It says `0%` on master (2620bb72a40ab7944102e3e4792d3ccec5afd669)

**Comment by GuillaumeFavelier** [comment]
Apparently https://github.com/pyvista/pyvistaqt/pull/32 is not enough either. I have the correct results when i calculate coverage locally and I don't see any issue with our `codecov.yml` :thinking:

**Comment by GuillaumeFavelier** [comment]
Does it work with a basic, default `codecov.yml` or no `codecov.yml` at all? I would like to start from a working version and iterate.

**Comment by akaszynski** [comment]
> Does it work with a basic, default `codecov.yml` or no `codecov.yml` at all? I would like to start from a working version and iterate.

It should work with the default `codecov.yml` or no `codecov.yml` as when it's missing it just defaults to the default `codecov.yml`.  Still not sure why this isn't working...
