### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by GuillaumeFavelier** [pyvista/pyvistaqt#30]
I think the [same question](https://github.com/pyvista/pyvista/issues/288) can be asked in this repo. And eventually the same solution could be applied.

**Comment by banesullivan** [comment]
It'd be easy to do it on this repo. I've used Black on other projects and have been enjoying it

**Comment by tkoyama010** [comment]
+1 for using Black.

**Comment by GuillaumeFavelier** [comment]
I notice some *real motivation* behind `black` 😅

To be honest, my nvim flake8 plugin is crying when I develop for pyvista and pyvistaqt so at this point, I am in favour of anything that can solve this 🙏

So, how does it work in terms of integration? What would be the plan?

**Comment by tkoyama010** [comment]
I made a PR which add CI of checking by black. Could you give opinion?

**Comment by GuillaumeFavelier** [comment]
Closing by #38
