### ISSUE TITLE
> We can still make `pylint` happy in a follow up PR if necessary 👍

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvistaqt#39]
> We can still make `pylint` happy in a follow up PR if necessary 👍

OK. Let's make pylint PR next time. Could you merge this PR first?

_Originally posted by @tkoyama010 in https://github.com/pyvista/pyvistaqt/pull/38#issuecomment-660034983_

**Comment by GuillaumeFavelier** [comment]
Closing by https://github.com/pyvista/pyvistaqt/pull/40
