### ISSUE TITLE
Project is not on PyPI yet

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvistaqt#4]
The project [is not on PyPI yet](https://pypi.org/project/pyvistaqt/), which is probably on purpose. I tried giving pyvista 0.25 a go, but my code uses `BackgroundPlotter`s, and so it tells me to install `pyvistaqt` from pip. And so does the README :) So right now the latest release of pyvista might lead users into a semi-dead end.

**Comment by banesullivan** [comment]
We can't launch this unto 0.25.1 of PyVista ships to PyPI. I believe @akaszynski is planning on releases this to PyPI right after PyVista which I think is happening today

**Comment by adeak** [comment]
Great, thanks for the information! I'll close this when it's up.

**Comment by akaszynski** [comment]
> Great, thanks for the information! I'll close this when it's up.

Yep, very soon.

**Comment by akaszynski** [comment]
It's up:
https://pypi.org/project/pyvistaqt/0.1.0/
