### ISSUE TITLE
Stage release for PyVista 0.40

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvistaqt#411]
Some changes have been made here to be compatible with PyVista 0.40, we should stage a release, @larsoner, do you want to handle this? I feel like you've done it recently and may be able to handle it easier/faster/safer than I

**Comment by larsoner** [comment]
Sure I can do that. But really I'd prefer to set up an automatic release based on tagged versions. I'll open a PR to add the infrastructure and make a secret, then if you do the release on GitHub we can see if it automagically works

**Comment by larsoner** [comment]
... and it already looks like we use `setuptools_scm` to the release process should automatically bump the version to `0.11.0` assuming you use that tag. I'll just do it after my PR merges and we'll see if it works

**Comment by larsoner** [comment]
Landed on PyPI https://pypi.org/project/pyvistaqt/0.11.0/
