### ISSUE TITLE
💚 Add Ipython test and check it in CI

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvistaqt#49]
@GuillaumeFavelier Thanks for your review. I am sorry that I could not find erorr of ipython. Could we add Ipython test and check it in CI? (It maybe another issue.)

_Originally posted by @tkoyama010 in https://github.com/pyvista/pyvistaqt/pull/40#issuecomment-675442699_

**Comment by GuillaumeFavelier** [comment]
I think creating a testing environment with IPython and plot a scene given by [`_create_testing_scene()`](https://github.com/pyvista/pyvistaqt/blob/659772c797e6e7ec4d6fa73d17b8b0eb720e582c/tests/test_plotting.py#L607-L641) would be a good start.

**Comment by tkoyama010** [comment]
It maybe a stupid question 😓  But could @pyvista/developers teach me how to make ipython environment ?

**Comment by GuillaumeFavelier** [comment]
Sorry if I misunderstand the question.

To start an IPython shell locally, this is what I do:

After installing it with:

```sh
$ pip install ipython
```
or:

```sh
$ conda install ipython
```

I just type:

```sh
$ ipython
```

Then I obtain the following:

```sh
Python 3.8.3 (default, May 19 2020, 18:47:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 
```

**Comment by tkoyama010** [comment]
@GuillaumeFavelier  This is exactry what I want to know. My concern was that it might require special procedures for pyvistaqt. Thanks.

**Comment by GuillaumeFavelier** [comment]
Closing by https://github.com/pyvista/pyvistaqt/pull/51
