### ISSUE TITLE
MAINT: Release?

### ISSUE THREAD

**Issue by larsoner** [pyvista/pyvistaqt#52]
It would be helpful to push out a release to get the latest icon updates (would probably fix [this segfault](https://travis-ci.org/github/mne-tools/mne-python/jobs/719590133#L5065) for example). I'm happy to do it if someone gives me permissions on PyPi. I'll just run a standard (for me at least) `python setup.py sdist bdist_wheel` and `twine upload dist/* --repository pyvistaqt --verbose` or so, unless there is more to it than that.

**Comment by GuillaumeFavelier** [comment]
+1 for a release. Usually, @akaszynski takes care of it.

**Comment by banesullivan** [comment]
I'd like to push out a new release of PyVista proper as well

**Comment by akaszynski** [comment]
We've automated releases with azure pipelines, so making a release (should) be as easy as:
```
git checkout master
git tag <version tag>
git push --tags
```

Our current tags are `0.1.0` and `0.1.1` and follow semantic versioning.  I've neglected the "v", and I've seen repositories use and not use it, so I think it's ok to exclude it.

We can follow pyvista's branching scheme as well if we wish to maintain a minor branch for patch releases for `pyvistaqt` as well, and maybe that's a good idea so we can rapidly push patch releases when necessary.  See [CONTRIBUTING.md](https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md)for more details on that.

**Comment by larsoner** [comment]
Probably need to change https://github.com/pyvista/pyvistaqt/blob/master/pyvistaqt/_version.py#L3, too, right?

**Comment by larsoner** [comment]
(Okay for me to change _version.py, tag 0.1.2, and push?)

**Comment by akaszynski** [comment]
Correct, and that's the only place where you need to change the version since that's read into `setup.py`.

If we're adding features and not just bug fixes, you're good to go to `0.2.0`.  Adding release notes on the releases page is always a good touch, but not necessary.

**Comment by larsoner** [comment]
Argh, tried to push with tags but failed because I need to make a PR -- the protected branch wouldn't let me push the `_version.py` directly to `master`. I'll try with a PR and tag force push, but might have to end up tagging + versioning `0.2.1` instead of `0.2.0` because I assumed I could direct push...

**Comment by akaszynski** [comment]
> Argh, tried to push with tags but failed because I need to make a PR -- the protected branch wouldn't let me push the `_version.py` directly to `master`. I'll try with a PR and tag force push, but might have to end up tagging + versioning `0.2.1` instead of `0.2.0` because I assumed I could direct push...

That's fine.  That's what patches are for.  Let me know if you need me to tag it and I'll get it done.

**Comment by akaszynski** [comment]
I saw the tag.  I'll just retag.  The pipeline will just redo the release.

**Comment by larsoner** [comment]
Indeed Azure seems to be having an issue with tags as of today

https://developercommunity.visualstudio.com/content/problem/1157675/tag-triggered-runs-failing-could-not-find-a-servic.html
