### ISSUE TITLE
BUG: Reference cycle problem with multiple windows open

### ISSUE THREAD

**Issue by larsoner** [pyvista/pyvistaqt#57]
This code:
```
import gc
import time
from pyvistaqt import BackgroundPlotter

plotters = list()
time.sleep(1)
for _ in range(20):
    plotter = BackgroundPlotter()
    plotter.show()
    plotters.append(plotter)
    #for plotter in plotters:
    plotter.close()
    plotter.deep_clean()
del plotter, plotters
gc.collect()
time.sleep(2)
```
Run with:
```
mprof run mem.py; mprof plot
```
Seems fine:

![Screenshot from 2020-09-18 09-18-31](https://user-images.githubusercontent.com/2365790/93602098-233c9080-f990-11ea-8ad4-bb17847a1ccd.png)

But when you uncomment the `for plotter in plotters` line and unindent it so that all plots are created, then all plots closed (rather than one created, one closed, repeating) we get:

![Screenshot from 2020-09-18 09-18-06](https://user-images.githubusercontent.com/2365790/93602152-3a7b7e00-f990-11ea-841e-67cfb7882f33.png)

In other words, there is ~150 MB in residual memory that cannot be cleared. I've spent some time trying to figure it out, no luck so far.

I know this seems like a minor problem, but when you have real plots and data [it matters](https://github.com/mne-tools/mne-python/pull/8266#issuecomment-694268011). Over in MNE we have an example that [opens about 20 windows at a time](https://mne.tools/0.19/auto_examples/visualization/plot_montage.html), and it causes a permanent ~1GB memory jump in a sphinx-gallery build -- it's the 1 GB step function around 1600 seconds here (I suspect most of our step jumps in doc builds are due to this):

![](https://user-images.githubusercontent.com/2365790/93483695-14da7000-f8cf-11ea-9e53-02bc7104cb84.png)

Here is a MNE-specfic example with real data and 10 plots, individual create-and-close:

![Screenshot from 2020-09-18 09-28-16](https://user-images.githubusercontent.com/2365790/93603045-76fba980-f991-11ea-88f4-a3ec0ea17a3a.png)

Create-all, close-all:

![Screenshot from 2020-09-18 09-26-18](https://user-images.githubusercontent.com/2365790/93603056-7c58f400-f991-11ea-9766-6638d0c22efa.png)

Even `mayavi` seems to have the problem, though:

![Screenshot from 2020-09-18 09-27-31](https://user-images.githubusercontent.com/2365790/93603083-84189880-f991-11ea-8f7f-5994ff30dfc2.png)

This makes me wonder if this is under the hood a problem with VTK's interactor class or something. Still, it would be nice to figure out what attributes could be deleted or tweaked to make it so that these can actually get garbage collected.

**Comment by GuillaumeFavelier** [comment]
Could it be related to `pyvista` `_ALL_PLOTTERS` variable? What happens if you try `pyvista.close_all()` at the end of the script?

**Comment by larsoner** [comment]
Same result (testing the PyVista minimal example, not the MNE ones, though I'm confident they will behave the same way):

![Screenshot from 2020-09-18 14-10-50](https://user-images.githubusercontent.com/2365790/93631010-e89b1e00-f9b8-11ea-87df-1a3e2db52d74.png)

**Comment by GuillaumeFavelier** [comment]
I tried resolving some reference cycles (decreasing the reference count: `self.interactor`, `self.frame`, `self.app_window`, ...), I tried force-freeing Qt objects ([`deleteLater()`](https://doc.qt.io/qt-5/qobject.html#deleteLater) and [`sip.delete()`](https://stackoverflow.com/questions/30241684/pyqt4-setparent-vs-deletelater/30245816#30245816)). I also looked at [`QVTKRenderWindowInteractor`](https://gitlab.kitware.com/vtk/vtk/-/blob/master/Wrapping/Python/vtkmodules/qt/QVTKRenderWindowInteractor.py), I tried the same approach with ref count (`_Iren`, `_RenderWindow`), explicitly deleting `_hidden` widget and calling (again) `Finalize()` to free vtk items.

What I did not try is to decrease the ref count of callables. From [stackoverflow](https://stackoverflow.com/questions/47941743/lifetime-of-object-in-lambda-connected-to-pyqtsignal):

> Note that when it comes to signal/slot connections, PyQt treats wrapped C++ slots and Python instance methods differently. The reference counts of these types of callable are not increased when they are connected to signals, whereas lambdas, defined functions, partial objects and static methods are. This means that if all other references to the latter types of callable are deleted, any remaining signal connections will keep them alive. Disconnecting the signals will allow such connected callables to be garbage-collected, if necessary.

I did not notice any significant improvement. Do you have any ideas @pyvista/developers ?

**Comment by GuillaumeFavelier** [comment]
I think https://github.com/pyvista/pyvistaqt/pull/66 could help with this especially if a test is designed for it. I'll do my best to go back on it when I can to make it move forward :+1:

**Comment by larsoner** [comment]
Pretty sure this is VTK+Qt's problem, not PyVista's. :(

Closing for https://gitlab.kitware.com/vtk/vtk/-/issues/18588 but I'll try to remember to report back here if it's ever fixed
