### ISSUE TITLE
Enable/Disable does not work?

### ISSUE THREAD

**Issue by GuillaumeFavelier** [pyvista/pyvistaqt#62]
Calling `disable()` should stop plotter interactions but the following stay interactive:

```py
import pyvista as pv
from pyvistaqt import BackgroundPlotter
p = BackgroundPlotter()
p.add_mesh(pv.Cube())
p.disable()  # <<< stop interactions here
p.show()
```

This follows https://github.com/pyvista/pyvista-support/issues/260#issuecomment-708479972

**Comment by banesullivan** [comment]
Ah, we may need to override those methods on the BackgrounPlotter to make sure the qtinteractor is disabled/enabled

**Comment by GuillaumeFavelier** [comment]
> make sure the qtinteractor is disabled/enabled

Do you know how to achieve that? I tried #63 without success so far
