### ISSUE TITLE
Segfault in podman container

### ISSUE THREAD

**Issue by brandon-feder** [pyvista/pyvistaqt#644]
I have built a container using podman and the following `Dockerfile`:
```
FROM debian:latest

RUN apt update
RUN apt -y install python3 python3-pip qt6-base-dev neovim
RUN pip install --break-system-packages \
    pyvista pyvistaqt PySide6 qtpy opencv-python qtawesome scikit-image

WORKDIR /mnt/workdir
```

When I start the container interactively, run `python3` and `import pyvistaqt`, I get a segfault with no error message.

**Comment by larsoner** [comment]
If in that same container you run for example `glxgears` or `python -c "import pyvista; print(pyvista.Report())"` do they succeed? If they don't then you don't have 3D support working properly yet so `pyvistaqt` won't be able to set up a GL context to use.

**Comment by brandon-feder** [comment]
You are exactly right. Upon setting up a GL context, everything works as expected.

**Comment by larsoner** [comment]
Okay great!
