### ISSUE TITLE
Import Error 'vtkGenericRenderWindowInteractor' from 'vtkmodules.vtkRenderingCore'

### ISSUE THREAD

**Issue by dominicjtriana** [pyvista/pyvistaqt#67]
I've done some reading of other issues and it seems like this was an issue with vtk before the update to vtk 9.0.1 but even though I have vtk 9.0.1 I'm still getting this error. It's hard to tell if this was resolved or not.  Is PySide2 supported or not...?  

I had an issue with PySide2 and my conda env which was fixed by installing the conda Pyside2 package.  I also installed the pyvistaqt conda package.  vtk package however says it's from pypi.  I tried updating this but it remained pypi.  Not sure if that makes things clearer.  

Full error:
```
Traceback (most recent call last):
  File "C:/Users/A9HALZZ/OneDrive - 3M/Nexus/Surface Scanner/Visualizer/pyvistaqt_example2.py", line 13, in <module>
    from pyvistaqt import QtInteractor
  File "C:\Users\A9HALZZ\Anaconda3\envs\scanPY38\lib\site-packages\pyvistaqt\__init__.py", line 3, in <module>
    from pyvistaqt.plotting import BackgroundPlotter, MainWindow, QtInteractor
  File "C:\Users\A9HALZZ\Anaconda3\envs\scanPY38\lib\site-packages\pyvistaqt\plotting.py", line 57, in <module>
    from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
  File "C:\Users\A9HALZZ\Anaconda3\envs\scanPY38\lib\site-packages\vtkmodules\qt\QVTKRenderWindowInteractor.py", line 62, in <module>
    from vtkmodules.vtkRenderingCore import vtkGenericRenderWindowInteractor, vtkRenderWindow
ImportError: cannot import name 'vtkGenericRenderWindowInteractor' from 'vtkmodules.vtkRenderingCore' (C:\Users\A9HALZZ\Anaconda3\envs\scanPY38\lib\site-packages\vtkmodules\vtkRenderingCore.cp38-win_amd64.pyd)
```

**Comment by nicobako** [comment]
So, I helped author #61. I updated the documentation to reflect the new qtpy support, but that only exists in the master branch, and will be available in the next release. If you use the master branch then pyvistaqt should work with qtpy.

 I only now realize that the documentation online is not in agreement with the current release of pyvistaqt.

**Comment by dominicjtriana** [comment]
> So, I helped author #61. I updated the documentation to reflect the new qtpy support, but that only exists in the master branch, and will be available in the next release. If you use the master branch then pyvistaqt should work with qtpy.
> 
> I only now realize that the documentation online is not in agreement with the current release of pyvistaqt.

Thanks for the reply.  I made fresh env and didn't use conda all packages install with pip.  Also added the clang path.  Now my error is different, "unexpected type 'PySide2.QtWidgets.QFrame'" which I saw was a previous issue.

Is this all related?  If I use PyQt5 it seems to work well, so should I just not use PySide2?

**Comment by nicobako** [comment]
Are you using the master branch of pyvistaqt, or are you using a version from pypi? In short, which version of pyvistaqt are you using?

**Comment by dominicjtriana** [comment]
> Are you using the master branch of pyvistaqt, or are you using a version from pypi? In short, which version of pyvistaqt are you using?

I'm using the pypi version atm.  I used conda-forge version too with similar issues.

**Comment by nicobako** [comment]
I think the issue is that the qtpy support is currently only in the master branch and not in any official release in pypi. The qtpy functionality will be incorporated into the next official release (0.3.0, I think). Unfortunately, the documentation online reflects the master branch and not the latest official release... I'm sorry about that.

If you want to use qtpy, then you will need to install the master branch. Otherwise, you could use pyqt5 for now and wait for the next release to use pyside2 (via qtpy). I hope this helps.

**Comment by dominicjtriana** [comment]
> If you want to use qtpy, then you will need to install the master branch. Otherwise, you could use pyqt5 for now and wait for the next release to use pyside2 (via qtpy). I hope this helps.

This does help a lot. At least I know I'm not going crazy...  If I wanted to use the master branch how would I do that?  I've very new to all of this.

**Comment by nicobako** [comment]
`pip` supports installing packages directly from a git repository. To learn more see https://pip.pypa.io/en/stable/reference/pip_install/#git

The command for installing the master branch of pyvistaqt with pip would be: `pip install git+https://github.com/pyvista/pyvistaqt.git@master#egg=pyvistaqt`

**Comment by dominicjtriana** [comment]
> The command for installing the master branch of pyvistaqt with pip would be: `pip install git+https://github.com/pyvista/pyvistaqt.git@master#egg=pyvistaqt`

Problem solved!  Thus ends my two day struggle.  Jesus H Christ.  Thanks again.

**Comment by nicobako** [comment]
I'm truly glad I could help! You may be the first person (besides me) to be using PySide2, so please let us know how it works for you. Your input is really appreciated.
