### ISSUE TITLE
Reimplement BackgroundPlotter to have each renderer in its own Qt frame

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvistaqt#7]
We should figure out how to reimplement the `BackgroundPlotter` to place several window interactors/renderers in their own Qt frames rather than as sub-viewports in a single interactor so that subplotting can be more configurable for downstream dependencies

- Qt frames can be dragged around/rearranged
- Each frame would have its own toolbar to fix how the "Save Camera" button only works for the last active view

@akaszynski, I think that you originally brought this up to me. Any thoughts?

**Comment by GuillaumeFavelier** [comment]
This is related to the `MultiPlotter` class in https://github.com/pyvista/pyvistaqt/pull/78
