### ISSUE TITLE
Pyside2 Example Error

### ISSUE THREAD

**Issue by lmarschall** [pyvista/pyvistaqt#72]
Heys guys,

at the moment im trying to implement a 3d tool to extract surfaces from 3d objects. There fore i want to utilize pyvista and pyside2 and integrate pyvistaqt with qml.

I wanted to start by setting up this example from the homepage: http://qtdocs.pyvista.org/usage.html#example-pyqt5-pyvista-qtinteractor, but unfortunaly there's the following error:

"QWidget(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'PySide2.QtWidgets.QFrame'"

There's my code(from the example):

```
import os
import sys

import vtkmodules.qt
os.environ["QT_API"] = "pyside2"

from PySide2 import QtWidgets
from PySide2.QtWidgets import QMainWindow

import numpy as np

import pyvista as pv
from pyvistaqt import QtInteractor

class MainWindow(QMainWindow):

    def __init__(self, parent=None, show=True):
        QtWidgets.QMainWindow.__init__(self, parent)

        # create the frame
        self.frame = QtWidgets.QFrame()
        vlayout = QtWidgets.QVBoxLayout()

        # add the pyvista interactor object
        self.plotter = QtInteractor(self.frame)
        vlayout.addWidget(self.plotter.interactor)

        self.frame.setLayout(vlayout)
        self.setCentralWidget(self.frame)

        # simple menu to demo functions
        mainMenu = self.menuBar()
        fileMenu = mainMenu.addMenu('File')
        exitButton = QtWidgets.QAction('Exit', self)
        exitButton.setShortcut('Ctrl+Q')
        exitButton.triggered.connect(self.close)
        fileMenu.addAction(exitButton)

        # allow adding a sphere
        meshMenu = mainMenu.addMenu('Mesh')
        self.add_sphere_action = QtWidgets.QAction('Add Sphere', self)
        self.add_sphere_action.triggered.connect(self.add_sphere)
        meshMenu.addAction(self.add_sphere_action)

        if show:
            self.show()

    def add_sphere(self):
        """ add a sphere to the pyqt frame """
        sphere = pv.Sphere()
        self.plotter.add_mesh(sphere, show_edges=True)
        self.plotter.reset_camera()


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    sys.exit(app.exec_())
```

This is my environment:

python: 3.6.7
pyside2: 5.13.2
pyqt: 5.12.3
pyvista: 0.27.2
pyvistaqt: 0.2.0

**Comment by nicobako** [comment]
Hey, I would recommend reviewing #67 . I think you're having the same issue. If so, sorry, it's absolutely my fault.

**Comment by lmarschall** [comment]
thank you for the fast response, so i used the pip install command provided in the issue, but my version seem not be changed, and there fore the error still occurs...

**Comment by nicobako** [comment]
I'll look into this (hopefully) tomorrow and see if I can figure out what's going on.

**Comment by nicobako** [comment]
@lmarschall, change your code to the following and you should be all good to go:

```python

import os
import sys

os.environ["QT_API"] = "pyside2"

from qtpy import QtWidgets
from qtpy.QtWidgets import QMainWindow

# note placement of `import vtkmodules.qt after importing qtpy stuff
import vtkmodules.qt

import numpy as np

import pyvista as pv
from pyvistaqt import QtInteractor

class MainWindow(QMainWindow):

    def __init__(self, parent=None, show=True):
        QtWidgets.QMainWindow.__init__(self, parent)

        # create the frame
        self.frame = QtWidgets.QFrame()
        vlayout = QtWidgets.QVBoxLayout()

        # add the pyvista interactor object
        self.plotter = QtInteractor(self.frame)
        vlayout.addWidget(self.plotter.interactor)

        self.frame.setLayout(vlayout)
        self.setCentralWidget(self.frame)

        # simple menu to demo functions
        mainMenu = self.menuBar()
        fileMenu = mainMenu.addMenu('File')
        exitButton = QtWidgets.QAction('Exit', self)
        exitButton.setShortcut('Ctrl+Q')
        exitButton.triggered.connect(self.close)
        fileMenu.addAction(exitButton)

        # allow adding a sphere
        meshMenu = mainMenu.addMenu('Mesh')
        self.add_sphere_action = QtWidgets.QAction('Add Sphere', self)
        self.add_sphere_action.triggered.connect(self.add_sphere)
        meshMenu.addAction(self.add_sphere_action)

        if show:
            self.show()

    def add_sphere(self):
        """ add a sphere to the pyqt frame """
        sphere = pv.Sphere()
        self.plotter.add_mesh(sphere, show_edges=True)
        self.plotter.reset_camera()

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    sys.exit(app.exec_())
```

You'll see that the biggest difference is where I `import vtkmodules.qt`. This **must** be done after you have imported the `qtpy` stuff. This is because `qtpy` performs some really crazy stuff for making sure that everything is set up properly for the Qt bindings that you want to use. When you do this:

```python
import vtkmodules.qt

os.environ["QT_API"] = "pyside2"

from qtpy import QtWidgets
from qtpy.QtWidgets import QMainWindow
...
```

you don't give `qtpy` time to setup the Qt bindings for `PySide2` properly. Instead, you have handed that task to `vtkmodules`, which obviously has made assumptions about the Qt bindings that don't agree with what you are trying to do. For example, note that this works:

```python
import vtkmodules.qt

os.environ["QT_API"] = "pyqt5"

from qtpy import QtWidgets
from qtpy.QtWidgets import QMainWindow
```

meaning that `vtkmodules` assumes `pyqt5` as its default Qt Bindings, not `PySide2`...

The other really important thing to note is that I don't `import PySide2` directly. Instead, I `import qtpy` objects. I may be completely wrong, but one of the benefits of using `qtpy` is that end users could decide to use `pyqt5` or `pyside2`, it's up to them. In this case, you are the *end user*. When you `import PySide2` objects you circumvent `qtpy`'s setup process, and make it impossible for end users to use `qtpy` to its fullest. I may be completely wrong here - I'm not a GUI developer nor a hardcore Qt user - but I think you should use the `qtpy` objects instead.

I hope this helps. Please let me know if you have any other questions, or if things are still not working for you.

**Comment by lmarschall** [comment]
hey nicobako,

i took your code and executed it with the following environment, unfortunately there's another error now :(

my environment:
python: 3.6.7
pyside2: 5.13.2
pyqt: 5.12.3
pyvista: 0.27.2
pyvistaqt: 0.2.0
qt: 5.12.9
qtpy: 1.9.0

my current error:
# add the pyvista interactor object
self.plotter = QtInteractor(self.frame)
QtInteractor cannot be converted to PyQt5.QtCore.QObject in this context

**Comment by nicobako** [comment]
Your error message says it's trying to convert it to a pyqt5 object. Either you're not running the code as written, or you still have not pip installed the master branch of pyvistaqt. The qtpy functionality is currently only available from the master branch of the GitHub repository. Try uninstalling pyvistaqt, then reinstalling it from the master branch following the directions in #67.

**Comment by lmarschall** [comment]
It works!

Sorry for the last error, that was me getting confused with all my testing environments. Finally i can proceed, thank you so much!
Maybe one last question, is there a plan to integrate qml view support into pyvistaqt?

**Comment by nicobako** [comment]
I don't know anything about qml view... That's a question for the core developpers of pyvistaqt.

**Comment by nicobako** [comment]
@lmarschall , do you feel comfortable closing this issue? Is your initial question resolved? If so, you can go ahead and close it yourself. Thanks!
