### ISSUE TITLE
Bug report: MacOS 10.15.7,PyVista QtInteractor example only works if window is hidden and then exposed

### ISSUE THREAD

**Issue by m-bob** [pyvista/pyvistaqt#73]
Hi,

Thanks for this code. When I invoke the example code from the command line, the menu is unresponsive until I cover (at least partially) the window with another window and then expose it. After that the app works great.

The "Add Sphere"menu item appears and everything works as it should.

Any ideas? (Note: I don't see this behavior with my other python QT5 codes. However, my other codes use PyQt5 directly and not qtpy. I expect the problem could be in qtpy.)

Thanks!

Murray

**Comment by m-bob** [comment]
I learned somethings that help. qtpy is irrelevant: I get the same behavior if I use PyQt5 directly.

Also, there is no problem if you invoke the python script using pythonw. If you use python3 the problem persists. I have no idea why that's so, but using pythonw "solves" the problem.

**Comment by nicobako** [comment]
Very interesting... Perhaps this is a *Mac-specific* issue?

Also, I have mentioned this in other issues, namely #72  and #67, but the *qtpy* functionality only exists in the master branch of *pyvistqt*, and is not yet available from the *pypi* package. I'm really sorry, I just haven't had the chance to update the documentation (perhaps I should do that now...). Make sure you have *pip install*-ed the master branch of *pyvistqt* and try the example code again.

Please read through those issues I linked above to get more explanations about the problem, and how to solve it.

As usual, let me know if thishelps.

**Comment by m-bob** [comment]
Thanks, Nico.

At present, I have no real need to use qtpy -- and the use of pythonw
solves my problem, so I'm good.

Please feel free to close the issue.

Murray

**Comment by nicobako** [comment]
> Please feel free to close the issue.

I actually can't close it... so if you feel like your problem is solved, go ahead and close it.

We really appreciate the feedback, and that you are using *pyvista* and *pyvistaqt*. Please feel free to reach out any time.

**Comment by m-bob** [comment]
Will do, thanks!
