### ISSUE TITLE
Support for PySide2 (qt)

### ISSUE THREAD

**Issue by RubendeBruin** [pyvista/pyvistaqt#8]
I would like to use pyvista in a qt qui application. In this application we use the pyside2 library instead of the pyqt5. Going over the source in qt_plotting it seems that adding support for pyside2 is not too much work. Willing to give it a go and create a merge request when finished.

However, I do not want to interfere withe pyvista/pyvista#614 which seems to propose massive reduction of the qt-related code in pyvista (which I think is a good idea).

Also, adding functionality to embed a plotter instance in an existing qt gui ( like done here: https://github.com/marcomusy/vtkplotter-examples/blob/master/vtkplotter_examples/other/qt_window.py ) is something I would like to add.

(see: https://www.learnpyqt.com/blog/pyqt5-vs-pyside2/)

Please tell me how and where I can support.

**Comment by GuillaumeFavelier** [comment]
And what do you think about [qtpy](https://github.com/spyder-ide/qtpy)?

**Comment by larsoner** [comment]
`qtpy` looks like a good option

**Comment by GuillaumeFavelier** [comment]
Closing by https://github.com/pyvista/pyvistaqt/pull/61
