### ISSUE TITLE
Unwanted memory usage by QtInteractor.add_point_labels

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvistaqt#87]
## Problem

I identified unwanted memory usage by `QtInterator.add_point_labels`, which is causing serious slowness in the interaction:

![image](https://user-images.githubusercontent.com/1608652/108265321-5eadd780-7147-11eb-8a9e-e5a71856f83b.png)

For reference, `QtInterator.add_mesh` produces:

![image](https://user-images.githubusercontent.com/1608652/108262744-15a85400-7144-11eb-912f-26492fa21426.png)

## Testing

I checked the memory use for the following cases using `examples.load_uniform` as `grid`:

1. plotting `grid` using `add_mesh` by `Plotter`
2. plotting `grid` using `add_mesh` by `QtInteractor`
3. plotting `grid.cell_centers` using `add_point_labels` by `Plotter`
4. plotting `grid.cell_centers` using `add_point_labels` by `QtInteractor`

Sources: [sources.zip](https://github.com/pyvista/pyvistaqt/files/5998404/sources.zip)

### Result of Case 1:

![image](https://user-images.githubusercontent.com/1608652/108261907-fd840500-7142-11eb-9ade-9631ab703753.png)

### Result of Case 2:

![image](https://user-images.githubusercontent.com/1608652/108261984-17bde300-7143-11eb-943c-703588fce21f.png)

### Result of Case 3:

![image](https://user-images.githubusercontent.com/1608652/108262039-2c9a7680-7143-11eb-9113-3de4851c1cda.png)

### Result of Case 4:

![image](https://user-images.githubusercontent.com/1608652/108262156-4dfb6280-7143-11eb-97c7-a724dea2ac3a.png)

## Scooby Report

```
--------------------------------------------------------------------------------
  Date: Wed Feb 17 16:57:11 2021 Hora oficial do Brasil

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.9 GB
       Environment : Python

  Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit
  (AMD64)]

           pyvista : 0.27.4
         pyvistaqt : 0.3.0
               vtk : 9.0.1
             numpy : 1.19.5
             scipy : 1.6.0
           IPython : 7.19.0
        matplotlib : 3.3.4
            scooby : 0.5.6
--------------------------------------------------------------------------------
```

**Comment by akaszynski** [comment]
Issue is due to the usage of `vtkSelectVisibilePoints`, which is a memory/cpu hog and is likely not very efficiently implemented (or is hard to implement).  Setting `always_visible=True` should help with the memory usage.

**Comment by rodrigomologni** [comment]
@akaszynski you're right! There is still memory usage. But now I can interact with the dataset. Thank you! 

![image](https://user-images.githubusercontent.com/1608652/108279354-41830400-715b-11eb-8cb5-fc865f9ad306.png)

**Comment by rodrigomologni** [comment]
Hi @akaszynski!

Would you know why this problem occurs with `QtInteractor` but not with `Plotter`? What do you think about changing the default value of `always_visible` to `True`? Or at least add an allert in the documentation of `always_visible` about this issue? I don't think I would have solved this problem if you hadn't helped me.
