### ISSUE TITLE
pyvistaqt install

### ISSUE THREAD

**Issue by zoner72** [pyvista/pyvistaqt#88]
Not sure if this can be classified as an issue.
On a clean windows 10 install I installed Anaconda (Anaconda3-2020.11-Windows-x86_64.exe)
After install, pyvista or pyvistaqt cannot be installed via the anaconda prompt (conda install -c conda-forge pyvistaqt) nor the Anaconda Navigator. 
PIP install gives an SSL error.
I can install other packages.
Over the same network, my laptop (which has a previously upgraded anaconda version) installs without problem (same on my work pc on a different network).

Does anyone have any idea what is wrong here,

**Comment by GuillaumeFavelier** [comment]
> Not sure if this can be classified as an issue.

Hi @zoner72 , I'll try to help anyway

> PIP install gives an SSL error.

Could you share the log?

Are you behind a proxy? After a short search online, I found the following:

```
pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org <package>
```

Reference: https://stackoverflow.com/questions/49943410/pip-ssl-error-on-windows

**Comment by zoner72** [comment]
@GuillaumeFavelier

thanks for your help

I will retry to reproduce the PIP error when Im back home (currently at work) and post the log.
I initially I thought it was my internal network (new router), but after I tried on the laptop and the install went perfect I realised it must be pc related. I tried again on my work PC without problem.

Since it is a clean install with only Anaconda and Pycharm on the PC, Im a bit surprised it did not work 'out of the box'.

I did try the link you posted yesterday

The only thing I can think off is that the other PC's have python 3.9.1 latest version installed in addition to the full Anaconda installation.

I was wondering if there is a procedure to manually install pyvistaqt

**Comment by GuillaumeFavelier** [comment]
> I tried again on my work PC without problem.

This is good to hear and is useful as baseline.

> The only thing I can think off is that the other PC's have python 3.9.1

Could be because of this. Although I just realize I missed the update of https://github.com/pyvista/pyvista/issues/1001, AFAIK `pyvistaqt` is not tested yet on `python=3.9.*`.

I just created a quick test env on my linux with:

```
conda create -n test-py39 python=3.9
```

And then I did:

```
conda activate test-py39
conda install -c conda-forge pyvista pyvistaqt
```

I was surprised to see that my basic script works as expected but I can't guarantee the same result on Windows.

As a short term solution, you could try on a different version of python.

It's just my guess unfortunately, the other @pyvista/developers might have a different perspective.

> I was wondering if there is a procedure to manually install pyvistaqt

You could also try to install the package from source?

```
git clone https://github.com/pyvista/pyvistaqt.git
cd pyvistaqt
python -m pip install -e .
```

*The commands above will install the latest version still in development.*

**Comment by zoner72** [comment]
**pip:**
```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyvistaqt/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyvistaqt/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyvistaqt/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyvistaqt/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyvistaqt/
Could not fetch URL https://pypi.org/simple/pyvistaqt/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pyvistaqt/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement pyvistaqt (from versions: none)
ERROR: No matching distribution found for pyvistaqt
```

**pip after stackoverflow solution has the same result (as above)**

**Anaconda:**
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
```


**Manual Install:**
great success!
I never realise this is how the manual install works, so will definitely bookmark this.
**pyvista** now shows in my Anaconda environment and can use **pyvistaq**t in my code.
However,  **pyvistaqt** does not show in my anaconda environment, not sure if this is how it is suppose to be.

Thanks again for your help, really appreciated.
I hope someone else can maybe solve the problem or solve their install problems
